name: "nyc_taxi"
version: "1.0.0"
config-version: 2

profile: "nyc_taxi"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Variables pour contrôler l'échantillonnage
vars:
  # Période d'échantillonnage (pour réduire la fenêtre temporelle)
  start_date: "2022-01-01"
  end_date: "2022-04-01" # 3 mois au lieu de 2 ans

  # Facteur d'échantillonnage (1 = 100%, 0.01 = 1%, etc.)
  taxi_sample_rate: 0.003 # ≈ 0.3% des données

  # Nombre de groupes NTILE pour l'échantillonnage stratifié
  ntile_groups: 1000
  selected_groups: 3 # Prendre les 3 premiers groupes

models:
  nyc_taxi:
    staging:
      materialized: view
      # Optimisations pour les vues d'échantillonnage
      +persist_docs:
        relation: true
        columns: true
    intermediate:
      materialized: view
      # Vues intermédiaires rapides
      +persist_docs:
        relation: true
        columns: true
    marts:
      materialized: table
      # Pas d'index automatique pour éviter les conflits de colonnes
      +post-hook: []
